<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Source - <?php echo basename($file) ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Zhangwei(hemono@gmail.com)">
    <style>
      body {
        overflow: auto;
        font-family: monospace;
        font-size: 12px;
      }
      code {
        overflow-x: auto;
        white-space: nowrap;
      }
        #line_emph {
            background-color: #bbbbff;
        }
        .num {
            border-right: 1px solid gray;
            color: gray;
            float: left;
            margin-right: 6pt;
            padding-right: 6pt;
            text-align: right;
            width: 25px;
            clear: left;
        }
    </style>
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.bootcss.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container-fluid">
    	<h1><?php echo $file?></h1>
    	<code>
        <?php if ($message==''):?>
    	<?php 
    	    $syntax = explode('<br />', str_replace(array('<code>', '</code>'), '', highlight_string($data, true)));
            foreach ($syntax as $num => $string): $num++;?>
                <span class="num" <?php if ($num==$line):?>id="line_emph"<?php endif; ?>><?php echo $num ?></span>
    			<?php echo $string; ?>
    			<br>
        <?php endforeach;?>
    	</code>
        <?php else:?>
        	<p><b><?php echo $message?></b></p>
        <?php endif?>
    </div>
    <script src="js/jquery-1.10.1.min.js"></script>
    <script>
        $(document).ready(function() { 
            var line_emph = $('#line_emph');
            if( line_emph.length > 0 ){
                var offset = line_emph.offset();
                $("html,body").animate({ scrollTop: offset.top-200 }, "fast");          
            }
        });
    </script>
</body>
</html>
