<?php
//"1D8BD1", "F1683C", "2AD62A", "DBDC25",  "649665", "4169E1", "087eb6", "BA55D3", "D2691E", "FF7F50",  "32CD32", "4682B4"
$call_style['Mysql'] = '1D8BD1';
$call_style['PDO'] = 'F1683C';
$call_style['PDOStatement'] = 'F1683C';
$call_style['Redis'] = '2AD62A';
$call_style['Memcache'] = 'DBDC25';
$call_style['Memcached'] = '649665';
$call_style['Curl'] = '4169E1';

?><!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>PHPIO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Zhangwei(hemono@gmail.com)">

    <!-- Le styles -->
    <!--link href="css/bootstrap.min.css" rel="stylesheet"-->
    <link href="css/fbootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        overflow: auto;
      }
    	.nav span.label {
    		/*position: absolute;*/
    		margin-left: 2px
    	}
      .prof_detail {
        display: none;
        height: 150px;
      }
      .show_detail,.prof_detail {
        background-color: #F5F5F5;
      }
      .prof_detail .tabbable .nav {
        margin: 0;
        padding: 0;
      }

      .label-class {
        text-indent: 1em;
        width: 3px;
        display: inline-block;
        margin-right: 3px;
      }

      .srclink {
        float: right;
      }

      .error {
        background-color: red;
      }

      .lr {
        word-wrap:break-word;
      }

      #function_table {
        table-layout:fixed;
      }

      .tab-pane pre {
        background-color: #F2F2F2;
        border: none;
        border-radius: none;
        display: block;
        font-size: 100%;
        margin: 0;
        padding: 0;
        white-space: pre-wrap;
        word-wrap: break-word;
      }

      .args_table {
        width:auto;
        max-width: 100%;
        border: 1px solid #ccc;
      }
<?php
foreach ( $call_style as $cls => $color ) {
	echo ".label-$cls{background-color:#$color}";
}
?>
    </style>
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.bootcss.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id="nav" class="topbar navbar-inverse navbar-fixed-top">
      <div class="topbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">PHPIO</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">ALL</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
        <table class="table table-hover condensed-table" id="function_table" cellspacing="0">
            <thead>
                <tr>
                    <th width=220><span>Function</span></th>
                    <th><span>Command</span></th>
                    <th width=220><span>Connection</span></th>
                    <th width=100><span>Response</span></th>
                    <th width=50><span>Time(ms)</span></th>
                </tr>
            </thead>
            <tbody>
            <?php
                foreach($data as $i => $row):
                  if ($i == 0) continue;

                  if ( isset($row['curl']) ) {
                      $row['header'] = file_get_contents($row['header']);
                      $row['link'] = curl_link($row['header']);
                  }

                  $traces = array();
                  foreach($row['trace'] as $trace) {
                      preg_match('|\[(.*?)\:(\d+)\]|', $trace, $matches);
                      $matches[0] = $trace;
                      $traces[] = $matches;
                  }
                ?>
                <tr id="prof_item_<?php echo $i?>" class="prof_item" data="<?php echo $row['classname']?>">
                  <td nowrap>
                    <a target="_blank" href="index.php?op=fileviewer&amp;file=<?php echo $matches[1]?>&amp;line=<?php echo $matches[2]?>" class="srclink" title="Show Source"><img alt="O" src="img/file.png"></a>
                    <i class="label-class label-<?php echo $row['classname'];?>">&nbsp;</i>
                    <a href="#"><?php echo (isset($row['class']) ? $row['class'].'->'.$row['function'] : $row['function']) ?></a>
                    <?php if(isset($row['error'])):?><span class="label error" title="<?php echo htmlspecialchars($row['error'])?>"><?php echo $row['errno']?></span><?php endif;?>
                  </td>
                  <td class="lr"><?php echo htmlspecialchars(isset($row['cmd']) ? $row['cmd'] : print_r($row['args'][0],true)) ?></td>
                  <td><?php echo $row['link'] ?></td>
                  <td><?php 
			$label_style = 'success';
			if(isset($row['error'])) {
				$label_style = 'error';
				echo '<span class="label '.$label_style.'" title="',htmlspecialchars($row['error']),'">',$row['errno'],'</span>';
			} elseif ( isset($row['rowcount']) ) {
				$label_style = ($row['rowcount'] == 0 ? 'warning' : $label_style);
				echo '<span class="label '.$label_style.'" title="',$row['rowcount'],' Affected Rows">ROWS(',$row['rowcount'],')</span>';
			} elseif ( isset($row['curl']) ) {
				$http_code = $row['curl']['http_code'];
				switch ( substr($http_code,0,1) ){
					case '1':
					case '2':
						break;
					case '3':
						$label_style = 'warning';
					case '4':
					case '5':
						$label_style = 'error';
				}
				$label_title = http_status($http_code);
				echo "<span class=\"label $label_style\" title=\"HTTP $http_code $label_title\">HTTP($http_code)</span>";
			} elseif ( isset($row['result']) ) {
				if ( preg_match('|(\w+)\((.+?)\)|',$row['result'], $matches) ) {
					list(,$type,$value) = $matches;
					switch ($type) {
						case 'bool':
							$label_style = ($value == 'false' ? 'error' : $label_style);
							echo '<span class="label '.$label_style.'">',$value,'</span>';break;
						default :
							echo '<span class="label '.$label_style.'">',$matches[0],'</span>';
					
					}
				} else {
					// NULL
					echo '<span class="label '.$label_style.'">',$row['result'],'</span>';
				}
			}
		?></td>
                  <td class="nr"><?php echo round((isset($row['curl']) ? $row['curl']['total_time'] : ($row['time_end']-$row['time_start']))*1000,4) ?></td>
                </tr>
                <tr id="prof_detail_<?php echo $i?>" class="prof_detail">
                  <td colspan=5>
                    <div class="tabbable">
                        <ul class="pills">
                        <li class="active"><a href="#traces<?php echo $i?>" data-toggle="tab">Traces</a></li>
                        <?php if(!empty($row['args'])): ?><li><a href="#args<?php echo $i?>" data-toggle="tab">Args</a></li><?php endif;?>
                        <?php if(isset($row['header'])): ?><li><a href="#header<?php echo $i?>" data-toggle="tab">Header</a></li><?php endif;?>
                        <?php if(!empty($row['curl'])): ?><li><a href="#curl<?php echo $i?>" data-toggle="tab">Curl</a></li><?php endif;?>
                        <li><a href="#response<?php echo $i?>" data-toggle="tab">Response</a></li>
                        </ul>
                        <div class="tab-content">
                        <div class="tab-pane active" id="traces<?php echo $i?>">
                          <ol>
                            <?php foreach($traces as $trace): ?>
                            <li><a target="_blank" href="index.php?op=fileviewer&amp;file=<?php echo $trace[1]?>&amp;line=<?php echo $trace[2]?>" title="Show Source"><?php echo $trace[0]?></a></li>
                          <?php endforeach;?>
                          </ol>
                        </div>
                        <?php if(isset($row['header'])): ?>
                        <div class="tab-pane" id="header<?php echo $i?>">
                          <pre><?php echo $row['header']; ?></pre>
                        </div>
                      <?php endif;?>
                      <?php if(!empty($row['args'])): ?>
                        <div class="tab-pane" id="args<?php echo $i?>">
                          <table class="args_table">
                            <thead>
                            <th>parameter </th>
                            <th>type</th>
                            <th>value</th>
                          </thead>
                          <tbody>
                            <?php foreach($row['args'] as $parameter => $value):?>
                            <tr>
                              <th><?php echo $parameter;?></th>
                              <td><?php echo gettype($value);?></td>
                              <td><pre><?php print_r($value);?></pre></td>
                            </tr>
                          <?php endforeach;?>
                          </tbody>
                        </table>
                        </div>
                        <?php endif;?>
                       <?php if(!empty($row['curl'])): ?>
                        <div class="tab-pane" id="curl<?php echo $i?>">
                          <table class="args_table">
                          <tbody>
                            <?php foreach($row['curl'] as $parameter => $value):?>
                            <tr>
                              <th><?php echo $parameter;?></th>
                              <td><pre><?php print_r($value);?></pre></td>
                            </tr>
                          <?php endforeach;?>
                          </tbody>
                        </table>
                        </div>
                        <?php endif;?>
 
                       <div class="tab-pane" id="response<?php echo $i?>"><pre><?php 
                          list($type, $content) = explode(" ", $row['result'], 2);
                          if ( substr($type, 0, 6) == 'string' ) {
                              echo '<b>',$type,'</b>','<br>', htmlspecialchars(substr($content,1,-1));
                          } else {
                              echo htmlspecialchars($row['result']);
                          }
                          ?></pre>
                        </div>
                        </div>
                    </div>
                  </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery-1.10.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/profile.js"></script>
  </body>
</html>
