<?php
//"1D8BD1", "F1683C", "2AD62A", "DBDC25",  "649665", "4169E1", "087eb6", "BA55D3", "D2691E", "FF7F50",  "32CD32", "4682B4"
$call_style['Mysql'] = '1D8BD1';
$call_style['PDO'] = 'F1683C';
$call_style['PDOStatement'] = 'F1683C';
$call_style['Redis'] = '2AD62A';
$call_style['Memcache'] = 'DBDC25';
$call_style['Memcached'] = '649665';
$call_style['Curl'] = '4169E1';

?><!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>PHPIO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Zhangwei(hemono@gmail.com)">

    <!-- Le styles -->
    <!--link href="css/bootstrap.min.css" rel="stylesheet"-->
    <link href="css/fbootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        overflow: auto;
      }
    	.nav span.label {
    		/*position: absolute;*/
    		margin-left: 2px
    	}
      .prof_detail {
        display: none;
        height: 150px;
      }
      .show_detail,.prof_detail,.show_detail .label-class {
        background-color: #F5F5F5;
      }
      .prof_detail .tabbable .nav {
        margin: 0;
        padding: 0;
      }

      .label-class {
        padding: 0;
        width: 1px;
      }

      .lr {
        word-wrap:break-word;
      }

      #function_table {
        table-layout:fixed;
      }

      .tab-pane pre {
        background-color: #F2F2F2;
        border: none;
        border-radius: none;
        display: block;
        font-size: 100%;
        margin: 0;
        padding: 0;
        white-space: pre-wrap;
        word-wrap: break-word;
      }
<?php
foreach ( $call_style as $cls => $color ) {
	echo ".label-$cls{background-color:#$color}";
}
?>
    </style>
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.bootcss.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id="nav" class="topbar navbar-inverse navbar-fixed-top">
      <div class="topbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">PHPIO</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">ALL</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
        <table class="table table-hover condensed-table" id="function_table" cellspacing="0">
            <thead>
                <tr>
                    <th width=1> </th>
                    <th width=150><span>Function</span></th>
                    <th width=10> </th>
                    <th><span>Command</span></th>
                    <th width=50><span>Time(ms)</span></th>
                </tr>
            </thead>
            <tbody>
            <?php
                for($i=1,$len=count($data); $i<$len; $i++):
                    if ( $i%2 == 0 ) continue;

                    $row = $data[$i];
                    $res = $data[$i+1];
                ?>
                <tr id="prof_item_<?php echo $i?>" class="prof_item" data="<?php echo $row['classname']?>">
                  <td class="label-class label-<?php echo $row['classname'];?>"></td>
                  <td><a href="#"><?php echo $row['function'] ?></a></td>
                  <td><a target="_blank" href="index.php?op=fileviewer&amp;file=<?php echo $match[1]?>&amp;line=<?php echo $match[2]?>" title="Show Source"><img alt="O" src="img/file.png"></a></td>
                  <td class="lr"><?php echo (isset($row['cmd']) ? $row['cmd'] : $row['args'][0]) ?></td>
                  <td class="nr"><?php echo round(($res['time']-$row['time'])*1000,4)?></td>
                </tr>
                <tr id="prof_detail_<?php echo $i?>" class="prof_detail">
                  <td colspan=5>
                    <div class="tabbable">
                        <ul class="pills">
                        <li class="active"><a href="#traces<?php echo $i?>" data-toggle="tab">Traces</a></li>
                        <?php if(isset($res['header'])): ?><li><a href="#header<?php echo $i?>" data-toggle="tab">Header</a></li><?php endif;?>
                        <?php if(!empty($row['args'])): ?><li><a href="#args<?php echo $i?>" data-toggle="tab">Args</a></li><?php endif;?>
                        <li><a href="#response<?php echo $i?>" data-toggle="tab">Response</a></li>
                        </ul>
                        <div class="tab-content">
                        <div class="tab-pane active" id="traces<?php echo $i?>">
                          <ol>
                            <?php 
                              foreach($row['trace'] as $j => $trace):
                                  preg_match('|\[(.*?)\:(\d+)\]|', $trace, $match);
                              ?>
                              <li><a target="_blank" href="index.php?op=fileviewer&amp;file=<?php echo $match[1]?>&amp;line=<?php echo $match[2]?>" title="Show source code"><?php echo $trace?></a></li>
                            <?php endforeach; ?>
                          </ol>
                        </div>
                        <?php if(isset($res['header'])): ?>
                        <div class="tab-pane" id="header<?php echo $i?>">
                          <pre><?php echo $res['header'] ?></pre>
                        </div>
                      <?php endif;?>
                      <?php if(!empty($row['args'])): ?>
                        <div class="tab-pane" id="args<?php echo $i?>">
                          <ol>
                            <?php foreach($row['args'] as $_arg):?>
                            <li><pre><?php var_export($_arg) ?></pre></li>
                          <?php endforeach;?>
                          </ol>
                        </div>
                        <?php endif;?>
                        <div class="tab-pane" id="response<?php echo $i?>">
                          <pre><?php echo htmlspecialchars($res['result'])?></pre>
                        </div>
                        </div>
                    </div>
                  </td>
                </tr>
                <?php endfor; ?>
            </tbody>
        </table>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery-1.10.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/profile.js"></script>
  </body>
</html>
