<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>PHPIO</title>
	<link rel="stylesheet" type="text/css" href="styles/style.css">
	<script src="js/jquery.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.blockUI.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.tablesorter.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.selectboxes.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/sprintf.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		function toggleCallInfo(functionNr){
			$("#callinfo_area_"+functionNr).toggle();
			current = $("#fold_marker_"+functionNr).get(0).src;
			if(current.substr(current.lastIndexOf('/')+1) == 'right.gif')
				$("#fold_marker_"+functionNr).get(0).src = 'img/down.gif';
			else
				$("#fold_marker_"+functionNr).get(0).src = 'img/right.gif';
		}
		
		function openCallInfo(functionNr) {
			var areaEl = $("#callinfo_area_"+functionNr);
			if (areaEl.length) {
    			if (areaEl.is(":hidden")) toggleCallInfo(functionNr);
    			window.scrollTo(0, areaEl.parent().offset().top);
    		}
		}

	</script>
</head>
<body>
    <div id="head">
        <div id="logo">
            <h1>PHPIO<sup style="font-size:10px">v<?php echo Webgrind_Config::$webgrindVersion?></sup></h1>
            <p>profiling in the browser</p>
        </div>
        <div id="options">
        </div>
        <div style="clear:both;"></div>
    </div>
    <div id="main">

        <div id="trace_view">
        	<div style="float:left;">
        	    <h2 id="invoke_url"></h2>
        	    <span id="data_file"></span> @ <span id="mtime"></span>
        	</div>
        	<div style="float:right;">
        	    <div id="breakdown" style="margin-bottom:5px;width:320px;height:20px"></div>
        	    <span id="invocation_sum"></span> different functions called in <span id="runtime_sum"></span> milliseconds (<span id="runs"></span> runs, <span id="shown_sum"></span> shown)
        	</div>
        	<div style="clear:both"></div>
        	<table class="tablesorter" id="function_table" cellspacing="0">
        		<thead>
        		    <tr>
        		        <th> </th>
        		        <th><span>Function</span></th>
        		        <th> </th>
        		        <th><span>Args</span></th>
        		        <th><span>Total Self Cost</span></th>
        		    </tr>
        		</thead>
        		<tbody>
					<?php
					$row_style[0] = 'even';
					$row_style[1] = 'odd';
					
					$call_style['Mysql'] = 'blue';
					$call_style['PDO'] = 'blue';
					$call_style['Redis'] = 'green';
					$call_style['Memcache'] = 'orange';
					$call_style['Memcached'] = 'orange';
					$call_style['Curl'] = 'wheat';
					
					foreach($data as $i => $row): 
						if ( $i%2 == 1 ) continue;
					?>
					<tr class="<?php echo $row_style[$i/2%2] ?>">
					  <td bgcolor="<?php echo $call_style[$row['class']];?>"></td>
					  <td><a href="javascript:toggleCallInfo(<?php echo $i?>)"> <img src="img/down.gif" id="fold_marker_<?php echo $i?>">
							  &nbsp;&nbsp;
							  <?php echo $row['class'],'::',$row['function'] ?>
						  </a>
						<div id="callinfo_area_<?php echo $i?>" class="callinfo_area" style="display: none;">
						  <table cellspacing="0" id="called_from_table_85" class="tablesorter">
							<thead>
							  <tr class="odd">
								<th class="header"><span>Called From</span></th>
								<th class=""> </th>
							  </tr>
							</thead>
							<tbody>
							  <?php foreach($row['trace'] as $i => $trace):
								  preg_match('|\[(.*?)\:(\d+)\]|', $trace, $match);
							  ?>
							  <tr class="<?php echo $row_style[$i%2] ?>">
								<td><?php echo $i?>&nbsp;&nbsp;<?php echo $trace?></td>
								<td><a target="_blank" href="index.php?op=fileviewer&amp;file=<?php echo $match[1]?>&amp;line=<?php echo $match[2]?>" title="Open file and show line"><img alt="O" src="img/file_line.png"></a></td>
							  </tr>
							  <?php endforeach;?>
							</tbody>
						  </table>
						</div></td>
					  <td><a target="_blank" href="index.php?op=fileviewer&amp;file=<?php echo $match[1]?>&amp;line=<?php echo $match[2]?>" title="Open file"><img alt="O" src="img/file.png"></a></td>
					  <td class="lr"><?php echo $row['args'][0]?></td>
					  <td class="nr"><?php echo round($row['t']*1000,4)?></td>
					</tr>
					<?php endforeach; ?>
        		</tbody>
        	</table>
        </div>
        <h2 id="hello_message">Select a cachegrind file above</h2>
        <div id="footer">
            <?php if(Webgrind_Config::$checkVersion):?>
        	<div id="version_info">&nbsp;</div>
        	<?php endif?>
            Copyright © 2013 Zhangwei(hemono@gmail.com). <a href="http://code.google.com/p/webgrind/">phpio homepage</a>
        </div>
    </div>
</body>
</html>